<?php
/**
 * Halo Email — Brief form
 * -----------------------------------------------------------------------------
 * Renders the email brief as an interactive form (sections 1-8). On submit it
 * builds a filled-in markdown brief (same shape as brief_sample.md), with the
 * Sender (§9) and Test targeting (§10) values hardcoded, and writes it to
 * ../submissions/. It does NOT download anything — the file is just saved.
 *
 * IMPORTANT: this is PHP — it must run on a PHP-capable host. GitHub Pages is
 * static and will NOT execute it. Deploy this file (and a writable
 * ../submissions/ folder) to your PHP server.
 * -----------------------------------------------------------------------------
 */

/* --- hardcoded send config (§9, §10) — not editable in the form --- */
const BRAZE_APP_ID = '575c10a7-11d8-4494-afdc-a01e5a420cf4';
const BRAZE_FROM   = 'The Halo Team <thehaloteam@app.halocollar.com>';
const TEST_SEGMENT = '31c76280-df2d-40c4-b566-e29117768163';

/* --- documentation base (live docs site) --- */
const DOCS = 'https://topdecileinc.github.io/halo-resources/README.html';

function field($k) { return isset($_POST[$k]) ? trim((string) $_POST[$k]) : ''; }

/** Flatten a value for safe use inside a single markdown table cell. */
function cell($s) {
    $s = trim($s);
    if ($s === '') return '';
    $s = preg_replace('/\s+/', ' ', $s);   // tables are single-line
    return str_replace('|', '\\|', $s);    // escape pipe so it doesn't break the table
}

/** Selected section names (multi-select checkboxes) joined for the brief cell. */
function sections_value() {
    $s = (isset($_POST['sections']) && is_array($_POST['sections'])) ? $_POST['sections'] : array();
    $s = array_filter(array_map('trim', $s), function ($x) { return $x !== ''; });
    return cell(implode(', ', $s));
}

/** Pre-flight: required-field and format checks run BEFORE any Claude call. Returns
    a list of problems; empty means the brief is complete enough to generate from.
    The automated pipeline has no human to ask, so an incomplete/invalid brief must be
    caught here rather than producing placeholder/non-compliant output downstream. */
function brief_problems() {
    // Only the campaign name is required (the form enforces it). Everything else is
    // optional and generated by Claude when blank, so there is nothing to block on
    // here — always let the generator try. Quality issues are caught after generation
    // by the gates, not by refusing to start.
    return array();
}

/* --- dynamic option lists, read live from the repo ----------------------------
   Segments come from brand-guidelines/rules_brand.md (Segment Definitions); §7 section options
   come from the section_*.html files in email-design-system/sections/ (each with
   its own <!-- section-desc: ... --> note). Apache's docroot may be the brief/
   directory, but PHP still reads these sibling files from the FILESYSTEM (they're
   not served over HTTP). If a file is missing or unreadable (e.g. open_basedir
   limits it), we fall back to a hardcoded list so the form never breaks. Editing
   those files updates the form on next load.
   ----------------------------------------------------------------------------- */
function repo_text($rel) {
    $p = __DIR__ . '/' . $rel;
    return (is_file($p) && is_readable($p)) ? @file_get_contents($p) : null;
}

/** Segment names — the `### ` headings under `## Segments` in the Segment Definitions section of rules_brand.md. */
function segment_list() {
    $fallback = array('Acquisition', 'Warm leads', 'New customers', 'Active / existing customers', 'Lapsed', 'Gold / premium members');
    $txt = repo_text('../brand-guidelines/rules_brand.md');
    if ($txt === null) return $fallback;
    $names = array(); $inSeg = false;
    foreach (preg_split('/\r?\n/', $txt) as $line) {
        if (preg_match('/^##\s+Segments\s*$/i', $line)) { $inSeg = true; continue; }
        if ($inSeg && preg_match('/^##\s+/', $line)) break;          // next H2 ends the section
        if ($inSeg && preg_match('/^###\s+(.+?)\s*$/', $line, $m)) $names[] = trim($m[1]);
    }
    return $names ? $names : $fallback;
}

/** Nameable §7 sections: every section_*.html (minus the always-on header/footer),
    each self-described by the `<!-- section-desc: ... -->` marker at the top of the file.
    The folder is the source of truth — drop a new section_*.html in and it shows up here,
    with its own description. (hero is driven by the §4 image; offer/pricing by §5 — those
    are NOT chosen here.) */
function section_list() {
    $fallback = array(
        'tech specs' => 'Key product specs in a stats panel.',
        'reviews'    => 'Customer reviews as quote cards.',
        'membership' => 'Membership / plan details.',
    );
    $out = array();
    foreach ((glob(__DIR__ . '/../email-design-system/sections/section_*.html') ?: array()) as $f) {
        $name = str_replace('_', ' ', preg_replace('/^section_|\.html$/', '', basename($f)));
        if (in_array(strtolower($name), array('header', 'footer'), true)) continue;   // always-on frame
        $desc = '';
        $txt = @file_get_contents($f);
        if ($txt !== false && preg_match('/section-desc:\s*(.+?)\s*-->/', $txt, $m)) {
            $desc = trim($m[1]);
        }
        $out[$name] = $desc;
    }
    ksort($out);
    return $out ? $out : $fallback;
}

/** Build the segment <select> from the live list. */
function segment_select() {
    $opts = '<option value="">—</option>';
    foreach (segment_list() as $s) {
        $e = htmlspecialchars($s, ENT_QUOTES, 'UTF-8');
        $opts .= '<option value="' . $e . '"' . pv_sel('target_segment', $s) . '>' . $e . '</option>';
    }
    return '<select id="target_segment" name="target_segment">' . $opts . '</select>';
}

/** Build the sections checkbox group from the live list. */
function sections_checks() {
    $html = '<div class="checks">'; $first = true;
    foreach (section_list() as $name => $note) {
        $eName = htmlspecialchars($name, ENT_QUOTES, 'UTF-8');
        $disp  = htmlspecialchars(ucfirst($name), ENT_QUOTES, 'UTF-8');
        $noteHtml = ($note !== '') ? ' <span class="opt-note">&mdash; ' . htmlspecialchars($note, ENT_QUOTES, 'UTF-8') . '</span>' : '';
        $id = $first ? ' id="f_sections"' : '';
        $checked = in_array($name, pv_sections(), true) ? ' checked' : '';
        $html .= '<label class="check"><input type="checkbox"' . $id . ' name="sections[]" value="' . $eName . '"' . $checked . '> ' . $disp . $noteHtml . '</label>';
        $first = false;
    }
    return $html . '</div>';
}

$isPost    = (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST');
$saveError = null;
$savedName = null;
$briefMd   = '';

// ---- how the form was opened (pre-fill + mode) ----
//   ?edit=<base> → editing an existing brief: Save/Generate OVERWRITES it (no duplicate).
//   ?copy=<base> → create a NEW brief pre-filled from an existing one (name suffixed "(copy)").
//   (none)       → a fresh, blank brief.
//   ?load=<base> is kept as an alias for ?edit= (older links + the preview's Retry button).
$prefill     = array();   // field => value, consumed by the control helpers below
$formMode    = 'new';     // 'new' | 'edit' | 'copy'
$editingBase = '';        // when editing, the exact brief base to overwrite
$openedFrom  = '';        // the source brief's display name (for the banner)
$fromVision    = false;   // true when the form was pre-filled by parsing a free-text vision
$parseError    = null;    // set if the vision parse failed
$parseRationale = array(); // the AI's per-field reasoning (shown in a collapsed window)
if (!$isPost) {
    $req = isset($_GET['edit']) ? array('edit', $_GET['edit'])
         : (isset($_GET['copy']) ? array('copy', $_GET['copy'])
         : (isset($_GET['load']) ? array('edit', $_GET['load']) : null));
    if ($req) {
        $bse = preg_replace('/\.md$/', '', basename((string) $req[1]));
        if (preg_match('/^brief_[a-z0-9_]+_\d{8}(?:_\d{6})?$/', $bse) && is_file(__DIR__ . '/../submissions/' . $bse . '.md')) {
            $prefill = brief_to_fields((string) @file_get_contents(__DIR__ . '/../submissions/' . $bse . '.md'));
            $openedFrom = isset($prefill['campaign_name']) ? $prefill['campaign_name'] : '';
            if ($req[0] === 'copy') {
                $formMode = 'copy';
                if ($openedFrom !== '') $prefill['campaign_name'] = $openedFrom . ' (copy)';   // a new brief
            } else {
                $formMode = 'edit';
                $editingBase = $bse;                                                           // overwrite this one
            }
        }
    }
}

if ($isPost) {
    @set_time_limit(0);              // generation + send can take a few minutes
    $gen = null; $mode = 'preview'; $sent = null; $sentEmail = null; $base = null;
    $cfgFile = __DIR__ . '/config.php';
    $cfg = is_file($cfgFile) ? require $cfgFile : null;
    $cfgReady = (is_array($cfg) && !empty($cfg['enabled']) && !empty($cfg['anthropic_api_key'])
                && strpos((string) $cfg['anthropic_api_key'], 'REPLACE') === false);
    $action = isset($_POST['action']) ? $_POST['action'] : 'brief';

    if ($action === 'send') {
        // ---- SEND a previously-generated email (chosen from the preview) ----
        $mode = 'sent';
        if ($cfgReady) {
            require_once __DIR__ . '/lib/claude_pipeline.php';
            $base = preg_replace('/[^a-z0-9_]/', '', basename((string) ($_POST['base'] ?? '')));
            $sent = hp_send_saved($cfg, $base);
            $sentEmail = hp_load_send_email($cfg, $base);
        } else {
            $sent = ['attempted' => false, 'ok' => false, 'code' => 0, 'message' => 'Generation is not configured (config.php).'];
        }
    } elseif ($action === 'ai_edit') {
        // ---- AI EDIT: revise the previewed email per a free-text instruction, then re-preview ----
        if ($cfgReady) {
            require_once __DIR__ . '/lib/claude_pipeline.php';
            $base = preg_replace('/[^a-z0-9_]/', '', basename((string) ($_POST['base'] ?? '')));
            $instruction = trim((string) ($_POST['instruction'] ?? ''));
            try { $gen = hp_edit_pipeline($cfg, $base, $instruction); }
            catch (Throwable $e) { $gen = ['ok' => false, 'error' => $e->getMessage()]; }
            $savedName = (!empty($gen['base']) ? $gen['base'] : $base) . '.md';   // for the "Retry — edit the brief" link
        } else {
            $gen = ['ok' => false, 'error' => 'Generation is not configured (config.php).'];
        }
    } elseif ($action === 'delete') {
        // ---- DELETE a saved brief and its generated email ----
        $mode = 'deleted';
        $deletedOk = false;
        $base = preg_replace('/[^a-z0-9_]/', '', basename((string) ($_POST['base'] ?? '')));
        if (preg_match('/^brief_[a-z0-9_]+_\d{8}(?:_\d{6})?$/', $base)) {
            @unlink(__DIR__ . '/../submissions/' . $base . '.md');
            @unlink(__DIR__ . '/../generated/' . $base . '.html');
            @unlink(__DIR__ . '/../generated/' . $base . '.send.json');
            $deletedOk = !is_file(__DIR__ . '/../submissions/' . $base . '.md');
        }
    } elseif ($action === 'parse') {
        // ---- PARSE a free-text campaign vision into a drafted brief, then show the form ----
        $fromVision = true;
        $vision = trim((string) ($_POST['vision'] ?? ''));
        if (!$cfgReady) {
            $parseError = 'drafting needs the Claude API (config.php)';
        } elseif ($vision === '') {
            $parseError = 'no description was entered';
        } else {
            require_once __DIR__ . '/lib/claude_pipeline.php';
            try {
                $res = hp_parse_brief($cfg, $vision, segment_list(), array_keys(section_list()));
                if (!empty($res['ok']) && is_array($res['fields'] ?? null)) {
                    $prefill = $res['fields'];
                    if (!empty($res['rationale']) && is_array($res['rationale'])) $parseRationale = $res['rationale'];
                } else {
                    $parseError = $res['error'] ?? 'could not draft the brief';
                }
            } catch (Throwable $e) {
                $parseError = $e->getMessage();
            }
        }
    } else {
        // ---- EDIT (overwrite the opened brief) or CREATE a new timestamped brief ----
        $campaign = field('campaign_name');
    $slug = strtolower($campaign !== '' ? $campaign : 'untitled');
    $slug = preg_replace('/[^a-z0-9]+/', '_', $slug);
    $slug = trim($slug, '_');
    if ($slug === '') $slug = 'untitled';
    $editing = preg_replace('/[^a-z0-9_]/', '', (string) ($_POST['editing'] ?? ''));
    if ($editing !== '' && preg_match('/^brief_[a-z0-9_]+_\d{8}(?:_\d{6})?$/', $editing)) {
        $base = $editing;                                    // EDIT: overwrite this brief + its email in place
    } else {
        $base = 'brief_' . $slug . '_' . date('Ymd_His');    // CREATE (new / copy): always a new file
    }
    $savedName = $base . '.md';

    $title = ($campaign !== '') ? $campaign : '[Campaign Name]';

    // ---- build the filled brief (mirrors brief_sample.md); §9 + §10 hardcoded ----
    $briefMd =
"---
---
# Email Brief — {$title}

## 1. Campaign basics

| Field | Your input |
|---|---|
| Brief name | " . cell(field('campaign_name')) . " |
| Subject | " . cell(field('subject')) . " |
| Occasion / theme | " . cell(field('occasion')) . " |
| Send date | " . cell(field('send_date')) . " |
| Primary goal | " . cell(field('primary_goal')) . " |

## 2. Audience

| Field | Your input |
|---|---|
| Target segment | " . cell(field('target_segment')) . " |

## 3. Content

| Field | Your input |
|---|---|
| Headline | " . cell(field('headline')) . " |
| Subhead | " . cell(field('subhead')) . " |

**Body copy** (the email body — use this verbatim when present):

" . trim(field('body')) . "

## 4. Hero image

| Field | Your input |
|---|---|
| Hosted hero URL | " . cell(field('hero_url')) . " |
| Alt text | " . cell(field('alt_text')) . " |

## 5. Pricing

| Field | Your input |
|---|---|
| Show pricing? | " . cell(field('show_pricing')) . " |
| Original price | " . cell(field('original_price')) . " |
| Sale / final price | " . cell(field('sale_price')) . " |
| Discount | " . cell(field('discount')) . " |
| Promo code | " . cell(field('promo_code')) . " |

## 6. Call to action

| # | CTA label | Destination |
|---|---|---|
| 1 | " . cell(field('cta1_label')) . " | " . cell(field('cta1_dest')) . " |
| 2 | " . cell(field('cta2_label')) . " | " . cell(field('cta2_dest')) . " |
| 3 | " . cell(field('cta3_label')) . " | " . cell(field('cta3_dest')) . " |

## 7. Structure & starting point

| Field | Your input |
|---|---|
| Start from a template? | " . cell(field('template')) . " |
| Sections to include | " . sections_value() . " |
| Anything to exclude | " . cell(field('exclude')) . " |

## 8. Notes for the builder

| Field | Your input |
|---|---|
| Notes | " . cell(field('notes')) . " |

## 9. Sender (for the Braze send)

| Field | Your input |
|---|---|
| Braze `app_id` | " . BRAZE_APP_ID . " |
| `from` | " . BRAZE_FROM . " |

> These are **not secrets**. The Braze API key and REST URL are **not** here — they live in
> brief/config.php on the server (see the README's \"Setup — Configure keys\" section).

## 10. Test targeting (segment)

Test sends target a designated test segment in a non-production Braze workspace.

| Field | Your input |
|---|---|
| Segment ID (UUID) | " . TEST_SEGMENT . " |
";

    // ---- save to ../submissions/ (no download — just save) ----
    $dir = __DIR__ . '/../submissions';
    if (!is_dir($dir)) { @mkdir($dir, 0775, true); }
    if (is_dir($dir) && is_writable($dir)) {
        if (@file_put_contents($dir . '/' . $savedName, $briefMd) === false) {
            $saveError = 'The brief could not be written to submissions/ (write failed).';
        }
    } else {
        $saveError = 'The submissions/ folder is missing or not writable on this server.';
    }

    // ---- "Save" only (draft) skips generation; "Save & generate" runs the pipeline ----
    $doSave = ((($_POST['do'] ?? '') === 'save'));
    if ($doSave) {
        // AJAX save (the usual path) returns JSON and stays on the page; a full "saved"
        // page is only used as a no-JS fallback.
        if (strtolower((string) ($_SERVER['HTTP_X_REQUESTED_WITH'] ?? '')) === 'xmlhttprequest') {
            header('Content-Type: application/json');
            echo json_encode([
                'ok'    => !$saveError,
                'base'  => $base,
                'name'  => ($title === '[Campaign Name]' ? '' : $title),
                'error' => $saveError,
            ]);
            exit;
        }
        if (!$saveError) $mode = 'saved';        // no-JS fallback
    } else {
        $preflight = $saveError ? array() : brief_problems();
        if ($preflight) {
            $gen = ['ok' => false, 'preflight' => true, 'errors' => $preflight];
        }
        if (!$saveError && !$preflight && $cfgReady) {
            require_once __DIR__ . '/lib/claude_pipeline.php';
            try {
                $gen = hp_run_pipeline($cfg, $briefMd, $base);
            } catch (Throwable $e) {
                $gen = ['ok' => false, 'error' => $e->getMessage()];
            }
        }
    }
    }  // end brief action
}

// Which view to render: the brief FORM (a vision parse, or an opened/edited/copied/new brief),
// otherwise the landing page (vision prompt + saved-briefs picker).
$showForm = ($isPost && isset($action) && $action === 'parse')
         || (!$isPost && ($formMode === 'edit' || $formMode === 'copy' || isset($_GET['new'])));

/**
 * Render one labelled field: label + summary + a docs link + the control.
 * Requiring $summary and $anchor here guarantees no field ships without both.
 */
function fld($label, $for, $summary, $anchor, $control) {
    $doc = DOCS . '#' . $anchor;
    echo '<div class="field">';
    echo '<label for="' . $for . '">' . $label . '</label>';
    echo '<span class="hint">' . $summary
       . ' <a class="doc-link" href="' . $doc . '" target="_blank" rel="noopener">Docs &#8599;</a></span>';
    echo $control;
    echo '</div>';
}

/* --- pre-fill helpers: read from $prefill (a saved brief parsed back into field values) --- */
function pv($k) { global $prefill; return isset($prefill[$k]) ? $prefill[$k] : ''; }
/** ` value="..."` for an <input>, or '' when there's nothing to pre-fill. */
function pv_attr($k) { $v = pv($k); return ($v === '' || is_array($v)) ? '' : ' value="' . htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8') . '"'; }
/** Escaped text for a <textarea> body or option compare. */
function pv_text($k) { $v = pv($k); return is_array($v) ? '' : htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); }
/** ` selected` when the saved value equals this option. */
function pv_sel($k, $opt) { $v = pv($k); return (!is_array($v) && (string) $v === (string) $opt) ? ' selected' : ''; }
/** The saved §7 sections as an array (for checkbox `checked`). */
function pv_sections() { global $prefill; $s = isset($prefill['sections']) ? $prefill['sections'] : array(); return is_array($s) ? $s : array(); }

/** Un-escape a markdown table cell that cell() wrote (it escaped `|` as `\|`). */
function brief_uncell($s) { return str_replace('\\|', '|', trim((string) $s)); }

/**
 * Parse a saved brief (the markdown form.php writes) back into form field values, so a brief
 * can be loaded into the form and adjusted. Mirrors the table layout built in the brief action.
 */
function brief_to_fields($md) {
    $out = array();
    $rows = array(
        'occasion'        => 'Occasion / theme',
        'send_date'       => 'Send date',
        'primary_goal'    => 'Primary goal',
        'target_segment'  => 'Target segment',
        'headline'        => 'Headline',
        'subhead'         => 'Subhead',
        'hero_url'        => 'Hosted hero URL',
        'alt_text'        => 'Alt text',
        'show_pricing'    => 'Show pricing?',
        'original_price'  => 'Original price',
        'sale_price'      => 'Sale / final price',
        'discount'        => 'Discount',
        'promo_code'      => 'Promo code',
        'template'        => 'Start from a template?',
        'exclude'         => 'Anything to exclude',
        'notes'           => 'Notes',
    );
    foreach ($rows as $key => $label) {
        if (preg_match('/^\|\s*' . preg_quote($label, '/') . '\s*\|\s*(.*?)\s*\|\s*$/m', $md, $m)) {
            $out[$key] = brief_uncell($m[1]);
        }
    }
    // brief name (label renamed from "Campaign name" to "Brief name"; accept either for old briefs)
    if (preg_match('/^\|\s*(?:Brief name|Campaign name)\s*\|\s*(.*?)\s*\|\s*$/m', $md, $m)) {
        $out['campaign_name'] = brief_uncell($m[1]);
    }
    // subject (this field is the email subject line; old briefs called it "Product / subject" or "Product")
    if (preg_match('/^\|\s*(?:Subject|Product \/ subject|Product)\s*\|\s*(.*?)\s*\|\s*$/m', $md, $m)) {
        $out['subject'] = brief_uncell($m[1]);
    }
    // body copy (a multi-line block after the §3 table; old briefs had a "Key message or offer" table cell)
    if (preg_match('/\*\*Body copy\*\*[^\n]*\n+(.*?)\s*(?:\n##\s|$)/s', $md, $m)) {
        $out['body'] = trim($m[1]);
    } elseif (preg_match('/^\|\s*Key message or offer\s*\|\s*(.*?)\s*\|\s*$/m', $md, $m)) {
        $out['body'] = brief_uncell($m[1]);
    }
    if (preg_match('/^\|\s*Sections to include\s*\|\s*(.*?)\s*\|\s*$/m', $md, $m)) {
        $val = brief_uncell($m[1]);
        $out['sections'] = ($val === '') ? array()
            : array_values(array_filter(array_map('trim', explode(',', $val)), function ($x) { return $x !== ''; }));
    }
    foreach (array(1, 2, 3) as $n) {
        if (preg_match('/^\|\s*' . $n . '\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$/m', $md, $m)) {
            $out['cta' . $n . '_label'] = brief_uncell($m[1]);
            $out['cta' . $n . '_dest']  = brief_uncell($m[2]);
        }
    }
    return $out;
}

/** Saved briefs in ../submissions/, newest first (capped at 100), each with its campaign
    title and a readable date — for the "Load a saved brief" search picker. */
function brief_files() {
    $dir = __DIR__ . '/../submissions';
    $files = glob($dir . '/brief_*.md') ?: array();
    rsort($files);                          // timestamped names → reverse-alpha = newest first
    $files = array_slice($files, 0, 100);
    $out = array();
    foreach ($files as $path) {
        $f = basename($path);
        $txt = (string) @file_get_contents($path);
        $title = '';
        if (preg_match('/^\|\s*(?:Brief name|Campaign name)\s*\|\s*(.*?)\s*\|\s*$/m', $txt, $m)) $title = brief_uncell($m[1]);
        if ($title === '' || $title === '[Campaign Name]') $title = '(untitled)';
        $when = '';
        if (preg_match('/_(\d{4})(\d{2})(\d{2})(?:_(\d{2})(\d{2})(\d{2}))?\.md$/', $f, $d)) {
            $when = $d[1] . '-' . $d[2] . '-' . $d[3] . (isset($d[4]) ? ' ' . $d[4] . ':' . $d[5] : '');
        }
        $out[] = array('file' => $f, 'title' => $title, 'when' => $when);
    }
    return $out;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Email brief form — Halo Email Resources</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;650;700;800&display=swap" rel="stylesheet">
<style>
  :root {
    --halo-font-sans: -apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", Roboto, Arial, sans-serif;
    --halo-font-mono: "SF Mono", Menlo, Consolas, monospace;
    --halo-ink: #071826;
    --halo-gray-700: #354c5c;
    --halo-gray-600: #526777;
    --halo-gray-300: #d3dce3;
    --halo-gray-200: #e2e9ee;
    --halo-gray-50: #fbfcfd;
    --halo-white: #ffffff;
    --halo-yellow: #fcd62d;
    --halo-blue: #2f93f3;
    --halo-radius-md: 8px;
    --halo-radius-lg: 12px;
    --halo-radius-pill: 999px;
  }
  *, *::before, *::after { box-sizing: border-box; }
  body {
    margin: 0; background: var(--halo-white); color: var(--halo-ink);
    font-family: var(--halo-font-sans); font-size: 16px; line-height: 1.6;
    -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  }
  a { color: var(--halo-blue); text-decoration: none; }
  a:hover { text-decoration: underline; }
  code { font-family: var(--halo-font-mono); font-size: 0.92em; }

  .halo-header {
    position: sticky; top: 0; z-index: 30;
    border-bottom: 1px solid var(--halo-gray-200);
    background: rgba(255,255,255,0.94);
    backdrop-filter: saturate(180%) blur(18px);
    -webkit-backdrop-filter: saturate(180%) blur(18px);
  }
  .halo-header__inner {
    width: min(900px, calc(100% - 32px)); margin-inline: auto; min-height: 64px;
    display: flex; align-items: center; gap: 16px;
  }
  .halo-header__inner img { width: 92px; height: auto; display: block; }
  .halo-header__tag { color: var(--halo-gray-600); font-weight: 800; letter-spacing: 0.04em; font-size: 0.9rem; }
  .halo-header__inner .spacer { flex: 1; }
  .halo-header__inner .home { font-weight: 650; font-size: 0.92rem; }
  .back { display: inline-block; margin-bottom: 16px; font-weight: 600; font-size: 0.9rem; }

  main { width: min(900px, calc(100% - 32px)); margin-inline: auto; padding: 40px 0 96px; }
  .lede { max-width: 62ch; color: var(--halo-gray-700); }
  h1 { font-size: 2rem; letter-spacing: -0.02em; margin: 0 0 8px; }

  form { margin-top: 8px; }
  /* collapsible sections (details/summary) */
  .fs {
    border: 1px solid var(--halo-gray-200); border-radius: var(--halo-radius-lg);
    margin: 0 0 14px; background: var(--halo-gray-50); overflow: hidden;
  }
  .fs > summary {
    list-style: none; cursor: pointer; user-select: none;
    display: flex; align-items: center; gap: 8px;
    padding: 15px 22px; font-weight: 800; font-size: 1.05rem; color: var(--halo-ink);
  }
  .fs > summary::-webkit-details-marker { display: none; }
  .fs > summary:hover { background: var(--halo-gray-200); }
  .fs > summary:focus-visible { outline: 2px solid var(--halo-blue); outline-offset: -2px; }
  .fs > summary .num { display: inline-block; min-width: 1.4em; color: var(--halo-blue); font-variant-numeric: tabular-nums; }
  .fs > summary::after {
    content: ""; margin-left: auto; width: 8px; height: 8px;
    border-right: 2px solid var(--halo-gray-600); border-bottom: 2px solid var(--halo-gray-600);
    transform: rotate(-45deg); transition: transform .18s;        /* points up when open */
  }
  .fs:not([open]) > summary::after { transform: rotate(45deg); }  /* points down when collapsed */
  .fs > *:not(summary) { padding-left: 22px; padding-right: 22px; }
  .fs > *:not(summary):last-child { padding-bottom: 14px; }
  .field { margin: 0 0 16px; }
  .field > label { display: block; font-weight: 650; font-size: 0.95rem; margin: 0 0 4px; }
  .field .hint { display: block; font-size: 0.82rem; color: var(--halo-gray-600); margin: 0 0 7px; font-weight: 400; }
  .field .doc-link { white-space: nowrap; font-weight: 600; }
  input[type=text], input[type=url], input[type=date], select, textarea {
    width: 100%; font: inherit; color: var(--halo-ink);
    padding: 10px 12px; background: var(--halo-white);
    border: 1px solid var(--halo-gray-300); border-radius: var(--halo-radius-md);
    transition: border-color 140ms, box-shadow 140ms;
  }
  textarea { min-height: 84px; resize: vertical; }
  input:focus, select:focus, textarea:focus {
    outline: none; border-color: var(--halo-blue); box-shadow: 0 0 0 3px rgba(47,147,243,0.18);
  }
  .checks { display: grid; gap: 8px; }
  .check {
    display: flex; align-items: center; gap: 10px; cursor: pointer;
    font-weight: 500; font-size: 0.92rem; background: var(--halo-white);
    border: 1px solid var(--halo-gray-300); border-radius: var(--halo-radius-md); padding: 9px 12px;
  }
  .check:hover { border-color: var(--halo-blue); }
  .check input { width: 16px; height: 16px; flex: none; cursor: pointer; }
  .check .opt-note { color: var(--halo-gray-600); font-weight: 400; }
  .req { color: #c0392b; }
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 0 18px; }
  .cta-row { display: grid; grid-template-columns: 1fr 1.4fr; gap: 0 18px; }
  @media (max-width: 560px) { .grid2, .cta-row { grid-template-columns: 1fr; } }

  .actions { margin-top: 8px; }
  .btn {
    display: inline-block; cursor: pointer; font: inherit; font-weight: 700;
    border: none; border-radius: var(--halo-radius-pill);
    padding: 14px 34px; background: var(--halo-yellow); color: #333;
    transition: transform 140ms, box-shadow 140ms;
  }
  .btn:hover { text-decoration: none; box-shadow: 0 6px 20px rgba(252,214,45,0.45); transform: translateY(-1px); }
  .btn--ghost { background: var(--halo-white); color: var(--halo-ink); border: 1px solid var(--halo-gray-300); }
  .btn:disabled { opacity: 0.65; cursor: progress; box-shadow: none; transform: none; }

  .email-preview { border: 1px solid var(--halo-gray-200); border-radius: var(--halo-radius-lg); overflow: hidden; margin-top: 18px; }
  .email-preview__bar { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 12px; border-bottom: 1px solid var(--halo-gray-200); background: var(--halo-gray-50); }
  .email-preview__label { font-size: 0.8rem; font-weight: 700; letter-spacing: 0.04em; color: var(--halo-gray-600); text-transform: uppercase; }
  .email-preview__toggle { display: inline-flex; border: 1px solid var(--halo-gray-300); border-radius: var(--halo-radius-pill); overflow: hidden; background: var(--halo-white); }
  .vw-btn { font: inherit; font-size: 0.82rem; font-weight: 600; cursor: pointer; border: 0; background: transparent; color: var(--halo-gray-600); padding: 6px 16px; }
  .vw-btn + .vw-btn { border-left: 1px solid var(--halo-gray-300); }
  .vw-btn.is-active { background: var(--halo-blue); color: #fff; }
  .email-preview__stage { background: #e9edee; padding: 16px; overflow: auto; }
  /* the email is a 600px design — show it at its true width (capped at 600), centered on a gray stage */
  .email-preview__frame { width: 600px; max-width: 100%; height: 640px; border: 0; display: block; margin: 0 auto; background: #fff; box-shadow: 0 6px 20px rgba(7,24,38,0.12); transition: width .2s ease; }

  /* full-screen processing overlay — blocks the form while generating + sending */
  .pg-loading {
    position: fixed; inset: 0; z-index: 100;
    display: none; align-items: center; justify-content: center;
    background: rgba(7, 24, 38, 0.78);
    backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px);
    padding: 24px;
  }
  .pg-loading.show { display: flex; }
  .pg-loading__card {
    background: var(--halo-white); border-radius: var(--halo-radius-lg);
    padding: 36px 40px; max-width: 460px; width: 100%; text-align: center;
    box-shadow: 0 24px 70px rgba(0,0,0,0.35);
  }
  .pg-loading__spinner {
    width: 46px; height: 46px; margin: 0 auto 22px;
    border: 4px solid var(--halo-gray-200); border-top-color: var(--halo-yellow);
    border-radius: 50%; animation: pg-spin 0.9s linear infinite;
  }
  @keyframes pg-spin { to { transform: rotate(360deg); } }
  .pg-loading__msg { margin: 0 0 8px; font-weight: 700; font-size: 1.12rem; color: var(--halo-ink); }
  .pg-loading__sub { margin: 0; font-size: 0.88rem; color: var(--halo-gray-600); line-height: 1.5; }
  @media (prefers-reduced-motion: reduce) { .pg-loading__spinner { animation-duration: 2.4s; } }

  .panel { border: 1px solid var(--halo-gray-200); border-radius: var(--halo-radius-lg); padding: 24px 26px; background: var(--halo-gray-50); }
  .panel.ok { border-color: #b7e0c2; background: #f3fbf5; }
  .panel.warn { border-color: #f1d59a; background: #fdf7ea; }
  .panel h2 { margin: 0 0 8px; font-size: 1.25rem; }
  .hardcoded { font-size: 0.85rem; color: var(--halo-gray-600); border-left: 3px solid var(--halo-gray-300); padding: 2px 0 2px 12px; margin: 4px 0 0; }
  pre.preview {
    margin-top: 18px; max-height: 320px; overflow: auto;
    background: var(--halo-white); border: 1px solid var(--halo-gray-200);
    border-radius: var(--halo-radius-md); padding: 14px 16px;
    font-family: var(--halo-font-mono); font-size: 0.82rem; line-height: 1.5; white-space: pre-wrap;
  }

  /* load-a-saved-brief search picker + loaded banner */
  .loadbar { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin: 4px 0 16px; }
  .combo { position: relative; width: 340px; max-width: 100%; }
  .combo input { width: 100%; font: inherit; color: var(--halo-ink); padding: 10px 12px; background: var(--halo-white); border: 1px solid var(--halo-gray-300); border-radius: var(--halo-radius-md); }
  .combo input:focus { outline: none; border-color: var(--halo-blue); box-shadow: 0 0 0 3px rgba(47,147,243,0.18); }
  .combo-list { list-style: none; margin: 6px 0 0; padding: 4px; max-height: 260px; overflow: auto; background: var(--halo-white); border: 1px solid var(--halo-gray-200); border-radius: var(--halo-radius-md); }
  /* JS upgrades the list to a focus-to-open dropdown; without JS it stays visible + scrollable */
  .combo.js-combo .combo-list { display: none; position: absolute; left: 0; right: 0; z-index: 40; box-shadow: 0 12px 30px rgba(0,0,0,0.12); }
  .combo.js-combo.open .combo-list { display: block; }
  .combo-list li[role="option"] { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; padding: 8px 10px; border-radius: 6px; cursor: pointer; }
  .combo-list li[role="option"]:hover, .combo-list li.active { background: var(--halo-gray-50); }
  .combo-list li.selected { background: rgba(47,147,243,0.12); }
  .combo-list li[role="option"] .t { font-weight: 600; font-size: 0.92rem; }
  .combo-list li[role="option"] .d { font-size: 0.78rem; color: var(--halo-gray-600); font-variant-numeric: tabular-nums; white-space: nowrap; }
  .combo-empty { padding: 8px 10px; font-size: 0.88rem; color: var(--halo-gray-600); }

  /* select-a-brief action bar */
  .brief-actions { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
  .brief-actions .btn { padding: 8px 20px; font-size: 0.9rem; }
  .btn--danger { background: #c0392b; color: #fff; }
  .btn--danger:hover { box-shadow: 0 6px 18px rgba(192,57,43,0.35); }
  .loaded-note { font-size: 0.88rem; color: var(--halo-gray-700); background: #f3fbf5; border: 1px solid #b7e0c2; border-radius: var(--halo-radius-md); padding: 8px 12px; margin: 0 0 18px; }
  .loaded-note--warn { background: #fdf7ea; border-color: #f1d59a; }

  /* landing: vision prompt + "or" divider */
  .vision { margin: 6px 0 8px; }
  .vision label { display: block; font-weight: 650; font-size: 0.95rem; margin: 0 0 6px; }
  .vision textarea { width: 100%; font: inherit; color: var(--halo-ink); padding: 12px 14px; background: var(--halo-white); border: 1px solid var(--halo-gray-300); border-radius: var(--halo-radius-md); resize: vertical; min-height: 110px; }
  .vision textarea:focus { outline: none; border-color: var(--halo-blue); box-shadow: 0 0 0 3px rgba(47,147,243,0.18); }
  .vision .actions { margin-top: 12px; }
  .lp-or { display: flex; align-items: center; gap: 14px; margin: 22px 0 14px; color: var(--halo-gray-600); font-size: 0.85rem; }
  .lp-or::before, .lp-or::after { content: ""; flex: 1; height: 1px; background: var(--halo-gray-200); }
  .lp-blank { margin-top: 18px; font-size: 0.9rem; }

  /* "why the AI filled these fields" window — collapsed by default */
  .rationale { border: 1px solid var(--halo-gray-200); border-radius: var(--halo-radius-md); background: var(--halo-white); margin: 0 0 18px; }
  .rationale > summary { list-style: none; cursor: pointer; user-select: none; display: flex; align-items: center; gap: 8px; padding: 10px 14px; font-weight: 650; font-size: 0.9rem; color: var(--halo-gray-700); }
  .rationale > summary::-webkit-details-marker { display: none; }
  .rationale > summary::after { content: ""; margin-left: auto; width: 7px; height: 7px; border-right: 2px solid var(--halo-gray-600); border-bottom: 2px solid var(--halo-gray-600); transform: rotate(45deg); transition: transform .18s; }
  .rationale[open] > summary::after { transform: rotate(-135deg); }
  .rationale ul { margin: 0; padding: 2px 16px 12px 32px; }
  .rationale li { font-size: 0.86rem; color: var(--halo-gray-700); line-height: 1.5; margin: 4px 0; }

  /* AI edit-with-a-prompt box on the preview */
  .ai-edit { margin-top: 16px; padding: 14px 16px; border: 1px solid var(--halo-gray-200); border-radius: var(--halo-radius-md); background: var(--halo-white); }
  .ai-edit label { display: block; font-weight: 650; font-size: 0.9rem; margin: 0 0 6px; }
  .ai-edit textarea { width: 100%; min-height: 60px; font: inherit; color: var(--halo-ink); padding: 10px 12px; border: 1px solid var(--halo-gray-300); border-radius: var(--halo-radius-md); resize: vertical; margin-bottom: 10px; }
  .ai-edit textarea:focus { outline: none; border-color: var(--halo-blue); box-shadow: 0 0 0 3px rgba(47,147,243,0.18); }

  /* save toast */
  .toast {
    position: fixed; right: 24px; bottom: 24px; z-index: 200;
    display: flex; align-items: flex-start; gap: 12px; max-width: 360px;
    padding: 14px 16px; background: var(--halo-white);
    border: 1px solid #b7e0c2; border-left: 4px solid #2fa157;
    border-radius: var(--halo-radius-lg); box-shadow: 0 16px 44px rgba(7,24,38,0.20);
    transform: translateY(14px); opacity: 0; pointer-events: none;
    transition: transform .22s ease, opacity .22s ease;
  }
  .toast.show { transform: translateY(0); opacity: 1; }
  .toast--error { border-color: #f1c0bb; border-left-color: #c0392b; }
  .toast__icon { flex: none; width: 24px; height: 24px; border-radius: 50%; background: #2fa157; color: #fff; font-size: 0.85rem; line-height: 24px; text-align: center; }
  .toast--error .toast__icon { background: #c0392b; }
  .toast__body { display: flex; flex-direction: column; gap: 2px; }
  .toast__title { font-size: 0.95rem; color: var(--halo-ink); }
  .toast__msg { font-size: 0.84rem; color: var(--halo-gray-700); }
  @media (prefers-reduced-motion: reduce) { .toast { transition: opacity .15s ease; transform: none; } }
</style>
</head>
<body>
  <header class="halo-header">
    <div class="halo-header__inner">
      <img src="https://topdecileinc.github.io/halo-resources/email-design-system/assets/shared-images/halo-logo-dark.svg" alt="Halo">
      <span class="halo-header__tag">EMAIL BRIEF</span>
      <span class="spacer"></span>
      <a class="home" href="https://topdecileinc.github.io/halo-resources/">All resources</a>
    </div>
  </header>

  <main>
    <a class="back" href="https://topdecileinc.github.io/halo-resources/">&larr; Back to all resources</a>
<?php if ($isPost && $action !== 'parse'): ?>

  <?php if ($mode === 'deleted'): ?>
    <div class="panel <?php echo !empty($deletedOk) ? 'ok' : 'warn'; ?>">
      <h2><?php echo !empty($deletedOk) ? '&#10003; Brief deleted' : '&#9888; Could not delete'; ?></h2>
      <p><?php echo !empty($deletedOk) ? 'The brief and its generated email were removed.' : 'The brief could not be deleted (it may already be gone).'; ?></p>
      <div class="actions" style="margin-top:16px;"><a class="btn btn--ghost" href="form.php">Back to briefs</a></div>
    </div>

  <?php elseif ($mode === 'saved'): ?>
    <div class="panel ok">
      <h2>&#10003; Brief saved</h2>
      <p>Saved <strong><?php echo htmlspecialchars(($title ?? '') === '[Campaign Name]' ? '(untitled)' : ($title ?? ''), ENT_QUOTES, 'UTF-8'); ?></strong> as a draft — no email generated. Pick it up anytime from <strong>Saved briefs</strong>.</p>
      <div class="actions" style="margin-top:16px; display:flex; gap:12px; flex-wrap:wrap;">
        <a class="btn" href="form.php?edit=<?php echo htmlspecialchars(urlencode(preg_replace('/\.md$/', '', $savedName ?? '')), ENT_QUOTES, 'UTF-8'); ?>">Keep editing</a>
        <a class="btn btn--ghost" href="form.php">New brief</a>
      </div>
    </div>

  <?php elseif ($mode === 'sent'): $sok = ($sent && !empty($sent['ok'])); ?>
    <!-- SENT confirmation -->
    <div class="panel <?php echo $sok ? 'ok' : 'warn'; ?>">
      <h2><?php echo $sok ? '&#10003; Sent' : '&#9888; Send failed — not sent'; ?></h2>
      <?php if ($sentEmail): ?>
        <p><strong>Subject:</strong> <?php echo htmlspecialchars($sentEmail['subject'], ENT_QUOTES, 'UTF-8'); ?></p>
        <p><strong>Preheader:</strong> <?php echo htmlspecialchars($sentEmail['preheader'], ENT_QUOTES, 'UTF-8'); ?></p>
      <?php endif; ?>
      <p><strong>Braze /messages/send:</strong> HTTP <?php echo (int) ($sent['code'] ?? 0); ?><?php echo (isset($sent['message']) && $sent['message'] !== '') ? ' — ' . htmlspecialchars($sent['message'], ENT_QUOTES, 'UTF-8') : ''; ?></p>
      <div class="actions" style="margin-top:16px;"><a class="btn btn--ghost" href="form.php">Start a new brief</a></div>
    </div>
    <?php if ($sentEmail && $sentEmail['html'] !== ''): ?>
      <div class="email-preview">
        <div class="email-preview__bar">
          <span class="email-preview__label">Email preview</span>
          <div class="email-preview__toggle" role="group" aria-label="Preview width">
            <button type="button" class="vw-btn is-active" data-w="600">Desktop</button>
            <button type="button" class="vw-btn" data-w="375">Mobile</button>
          </div>
        </div>
        <div class="email-preview__stage">
          <iframe class="email-preview__frame" srcdoc="<?php echo htmlspecialchars($sentEmail['html'], ENT_QUOTES, 'UTF-8'); ?>" title="Sent email preview"></iframe>
        </div>
      </div>
    <?php endif; ?>

  <?php elseif ($gen !== null && !empty($gen['ok'])): ?>
    <!-- PREVIEW: generated, ready to review → redo or send -->
    <div class="panel ok">
      <h2>&#10003; Email generated &mdash; review &amp; send</h2>
      <?php
        $previewTitle = '';
        if (!empty($savedName) && is_file(__DIR__ . '/../submissions/' . $savedName)) {
            $pf2 = brief_to_fields((string) @file_get_contents(__DIR__ . '/../submissions/' . $savedName));
            if (isset($pf2['campaign_name'])) $previewTitle = $pf2['campaign_name'];
        }
        if ($previewTitle === '' || $previewTitle === '[Campaign Name]') $previewTitle = '(untitled)';
      ?>
      <p><strong>Campaign:</strong> <?php echo htmlspecialchars($previewTitle, ENT_QUOTES, 'UTF-8'); ?></p>
      <p><strong>Subject:</strong> <?php echo htmlspecialchars($gen['subject'], ENT_QUOTES, 'UTF-8'); ?></p>
      <p><strong>Preheader:</strong> <?php echo htmlspecialchars($gen['preheader'], ENT_QUOTES, 'UTF-8'); ?></p>
      <?php if (!empty($gen['validated'])): ?>
        <p class="hardcoded">&#10003; Passed all validation checks<?php echo ((int) ($gen['attempts'] ?? 1) > 1) ? ' (on attempt ' . (int) $gen['attempts'] . ')' : ''; ?>.</p>
      <?php endif; ?>
      <?php if (!empty($gen['advisories'])): ?>
        <details style="margin-top:8px;">
          <summary style="cursor:pointer; font-weight:650; font-size:0.9rem; color:var(--halo-gray-700);">AI review notes — advisory, did <strong>not</strong> block (<?php echo count($gen['advisories']); ?>)</summary>
          <ul style="margin:8px 0 4px 18px;">
            <?php foreach ($gen['advisories'] as $a): ?>
              <li style="font-size:0.88rem; color:var(--halo-gray-700);"><?php echo htmlspecialchars($a, ENT_QUOTES, 'UTF-8'); ?></li>
            <?php endforeach; ?>
          </ul>
        </details>
      <?php endif; ?>
      <?php if (!empty($gen['ai_error'])): ?>
        <p class="hardcoded">Note: the AI review pass couldn't run (advisory, didn't block): <?php echo htmlspecialchars($gen['ai_error'], ENT_QUOTES, 'UTF-8'); ?></p>
      <?php endif; ?>
      <?php if (!empty($gen['truncated'])): ?>
        <p class="hardcoded">&#9888; Output hit the token limit and may be truncated — raise <code>max_tokens</code> in config.php.</p>
      <?php endif; ?>
      <p class="hardcoded" style="margin-top:8px;">Nothing has been sent yet. Saved to <code>generated/<?php echo htmlspecialchars($gen['html_file'] ?? '', ENT_QUOTES, 'UTF-8'); ?></code>. Review the preview below, then retry the brief or send.</p>

      <?php /* AI edit prompt box — commented out for the demo. Re-enable by changing the
               next line to `if (true):`. The ai_edit handler + hp_edit_pipeline stay in place. */ ?>
      <?php if (false): ?>
      <form method="post" action="" data-overlay="edit" class="ai-edit">
        <input type="hidden" name="action" value="ai_edit">
        <input type="hidden" name="base" value="<?php echo htmlspecialchars($gen['base'] ?? '', ENT_QUOTES, 'UTF-8'); ?>">
        <label for="instruction">Edit with a prompt</label>
        <textarea id="instruction" name="instruction" required placeholder="e.g. Make the CTA button blue and shorten the intro to one sentence."></textarea>
        <button type="submit" class="btn btn--ghost">Apply edit</button>
      </form>
      <?php endif; ?>

      <div class="actions" style="margin-top:16px; display:flex; gap:12px; flex-wrap:wrap;">
        <form method="post" action="" data-overlay="send" style="margin:0;">
          <input type="hidden" name="action" value="send">
          <input type="hidden" name="base" value="<?php echo htmlspecialchars($gen['base'] ?? '', ENT_QUOTES, 'UTF-8'); ?>">
          <button type="submit" class="btn">Send this email</button>
        </form>
        <a class="btn btn--ghost" href="form.php?load=<?php echo htmlspecialchars(urlencode($savedName ?? ''), ENT_QUOTES, 'UTF-8'); ?>">Retry &mdash; edit the brief</a>
        <a class="btn btn--ghost" href="form.php">New brief</a>
      </div>
    </div>
    <div class="email-preview">
      <div class="email-preview__bar">
        <span class="email-preview__label">Email preview</span>
        <div class="email-preview__toggle" role="group" aria-label="Preview width">
          <button type="button" class="vw-btn is-active" data-w="600">Desktop</button>
          <button type="button" class="vw-btn" data-w="375">Mobile</button>
        </div>
      </div>
      <div class="email-preview__stage">
        <iframe class="email-preview__frame" srcdoc="<?php echo htmlspecialchars($gen['html'] ?? '', ENT_QUOTES, 'UTF-8'); ?>" title="Email preview"></iframe>
      </div>
    </div>
    <?php if (!empty($gen['loaded'])): ?>
      <details style="margin-top:12px;">
        <summary style="cursor:pointer; font-weight:650; font-size:0.9rem; color:var(--halo-gray-700);">Context loaded into Claude (<?php echo count($gen['loaded']); ?> files)</summary>
        <pre class="preview"><?php echo htmlspecialchars(implode("\n", $gen['loaded']), ENT_QUOTES, 'UTF-8'); ?></pre>
      </details>
    <?php endif; ?>

  <?php elseif ($gen !== null && !empty($gen['preflight'])): ?>
    <div class="panel warn">
      <h2>&#9888; Brief incomplete — nothing generated</h2>
      <p>It's missing required information, so it was <strong>not</strong> sent to the generator. Fix these and resubmit:</p>
      <ul style="margin:0 0 4px 18px;">
        <?php foreach (($gen['errors'] ?? []) as $erow): ?>
          <li style="font-size:0.9rem;"><?php echo htmlspecialchars($erow, ENT_QUOTES, 'UTF-8'); ?></li>
        <?php endforeach; ?>
      </ul>
      <div class="actions" style="margin-top:16px;"><a class="btn btn--ghost" href="form.php">Back to the brief</a></div>
    </div>

  <?php elseif ($gen !== null && !empty($gen['validation_failed'])): ?>
    <div class="panel warn">
      <h2>&#9888; Couldn&rsquo;t generate a compliant email &mdash; not sent</h2>
      <p>After <?php echo (int) ($gen['attempts'] ?? 2); ?> attempts the email still broke binding rules, so it was <strong>not sent</strong>. The last attempt is in <code>generated/<?php echo htmlspecialchars($gen['html_file'] ?? '', ENT_QUOTES, 'UTF-8'); ?></code> for review.</p>
      <p style="margin-bottom:6px;"><strong>Rules it failed:</strong></p>
      <ul style="margin:0 0 4px 18px;">
        <?php foreach (($gen['errors'] ?? []) as $erow): ?>
          <li style="font-size:0.9rem;"><?php echo htmlspecialchars($erow, ENT_QUOTES, 'UTF-8'); ?></li>
        <?php endforeach; ?>
      </ul>
      <div class="actions" style="margin-top:16px; display:flex; gap:12px; flex-wrap:wrap;">
        <?php if (!empty($savedName)): ?>
        <a class="btn btn--ghost" href="form.php?load=<?php echo htmlspecialchars(urlencode($savedName), ENT_QUOTES, 'UTF-8'); ?>">Retry &mdash; edit the brief</a>
        <?php endif; ?>
        <a class="btn btn--ghost" href="form.php">New brief</a>
      </div>
    </div>

  <?php elseif ($gen !== null): ?>
    <div class="panel warn">
      <h2>&#9888; Email generation failed</h2>
      <p><em><?php echo htmlspecialchars($gen['error'] ?? 'Unknown error', ENT_QUOTES, 'UTF-8'); ?></em></p>
      <div class="actions" style="margin-top:16px;"><a class="btn btn--ghost" href="form.php">Back to the brief</a></div>
    </div>

  <?php else: ?>
    <!-- brief saved, but generation not configured -->
    <div class="panel <?php echo $saveError ? 'warn' : 'ok'; ?>">
      <h2><?php echo $saveError ? '&#9888; Brief built — but not saved' : '&#10003; Brief saved'; ?></h2>
      <?php if ($saveError): ?>
        <p><em><?php echo htmlspecialchars($saveError, ENT_QUOTES, 'UTF-8'); ?></em></p>
      <?php else: ?>
        <p>Saved to <code>submissions/<?php echo htmlspecialchars($savedName ?? '', ENT_QUOTES, 'UTF-8'); ?></code>. Automated generation isn't configured (no <code>config.php</code>).</p>
      <?php endif; ?>
      <div class="actions" style="margin-top:16px;"><a class="btn btn--ghost" href="form.php">Start a new brief</a></div>
      <pre class="preview"><?php echo htmlspecialchars($briefMd ?? '', ENT_QUOTES, 'UTF-8'); ?></pre>
    </div>
  <?php endif; ?>

<?php elseif ($showForm): ?>
    <h1>Email brief</h1>
    <?php if (!empty($fromVision) && empty($parseError)): ?>
      <p class="loaded-note">Drafted from your description &mdash; <strong>review and edit</strong> anything below, then Save or Save &amp; generate.</p>
    <?php elseif (!empty($parseError)): ?>
      <p class="loaded-note loaded-note--warn">Couldn&rsquo;t draft from your description (<?php echo htmlspecialchars($parseError, ENT_QUOTES, 'UTF-8'); ?>). Fill it in below.</p>
    <?php else: ?>
      <p class="lede">Fill this in for one campaign. Leave anything blank that doesn&rsquo;t apply &mdash; the generator drafts the rest. Every field links to its documentation.</p>
    <?php endif; ?>
    <?php if (!empty($parseRationale)): ?>
      <details class="rationale">
        <summary>Why the AI filled these fields</summary>
        <ul>
          <?php foreach ($parseRationale as $r): ?>
            <li><?php echo htmlspecialchars($r, ENT_QUOTES, 'UTF-8'); ?></li>
          <?php endforeach; ?>
        </ul>
      </details>
    <?php endif; ?>
    <?php if ($formMode === 'edit'): ?>
      <p class="loaded-note">Editing <strong><?php echo htmlspecialchars($openedFrom !== '' ? $openedFrom : '(untitled)', ENT_QUOTES, 'UTF-8'); ?></strong> — saving will <strong>update this brief</strong> (no duplicate). <a href="form.php?new">New brief instead</a>.</p>
    <?php elseif ($formMode === 'copy'): ?>
      <p class="loaded-note">Copying from <strong><?php echo htmlspecialchars($openedFrom !== '' ? $openedFrom : '(untitled)', ENT_QUOTES, 'UTF-8'); ?></strong> — this saves as a <strong>new brief</strong>; the original is untouched. <a href="form.php?new">New blank brief</a>.</p>
    <?php endif; ?>

    <form method="post" action="" autocomplete="off" id="brief-form">
      <input type="hidden" name="editing" value="<?php echo htmlspecialchars($editingBase, ENT_QUOTES, 'UTF-8'); ?>">

      <details class="fs" open>
        <summary><span class="num">1</span>Campaign basics</summary>
        <?php
          fld('Brief name <span class="req">*</span>', 'campaign_name',
              'A short name to identify this brief — it names the saved file and shows in the picker. It does NOT appear in the email.',
              '1-campaign-basics',
              '<input type="text" id="campaign_name" name="campaign_name" required' . pv_attr('campaign_name') . '>');
          fld('Subject', 'subject',
              'The email subject line. The AI drafts one from your campaign — edit it here. Keep it short (~50 chars), warm, no em dashes. Leave blank to auto-generate.',
              '1-campaign-basics',
              '<input type="text" id="subject" name="subject"' . pv_attr('subject') . '>');
          fld('Occasion / theme', 'occasion',
              'The hook or timing — holiday, awareness month, flash sale, or evergreen.',
              '1-campaign-basics',
              '<input type="text" id="occasion" name="occasion"' . pv_attr('occasion') . '>');
          fld('Send date', 'send_date',
              'The date this email is scheduled to go out.',
              '1-campaign-basics',
              '<input type="date" id="send_date" name="send_date"' . pv_attr('send_date') . '>');
          fld('Primary goal', 'primary_goal',
              'The one outcome this email is for — drive a purchase, re-engage, or announce a feature.',
              '1-campaign-basics',
              '<input type="text" id="primary_goal" name="primary_goal"' . pv_attr('primary_goal') . '>');
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">2</span>Audience</summary>
        <?php
          fld('Target segment', 'target_segment',
              'Which defined audience segment this email targets. The segment shapes the angle, tone, and offer. Options are read live from rules_brand.md (Segment Definitions).',
              '2-audience--segments',
              segment_select());
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">3</span>Content</summary>
        <?php
          fld('Headline', 'headline',
              'The main headline. Leave blank to auto-generate one to match the campaign and segment.',
              '3-content',
              '<input type="text" id="headline" name="headline"' . pv_attr('headline') . '>');
          fld('Subhead', 'subhead',
              'The supporting line under the headline. Leave blank to auto-generate (or omit).',
              '3-content',
              '<input type="text" id="subhead" name="subhead"' . pv_attr('subhead') . '>');
          fld('Body copy', 'body',
              'The email body copy. The AI drafts it from your campaign — edit it here, and the email uses what you write (state the offer/price in plain terms). Leave blank to auto-generate.',
              '3-content',
              '<textarea id="body" name="body" rows="7">' . pv_text('body') . '</textarea>');
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">4</span>Hero image</summary>
        <?php
          fld('Hosted hero URL', 'hero_url',
              'The live, hosted URL of the hero image the email links to (not an upload).',
              '4-hero-image-hosted-url--reference-upload',
              '<input type="url" id="hero_url" name="hero_url" placeholder="https://… (PNG / JPG / GIF — not .webp)"' . pv_attr('hero_url') . '>');
          fld('Alt text', 'alt_text',
              'A short description of the hero image for accessibility and Outlook fallback.',
              '4-hero-image-hosted-url--reference-upload',
              '<input type="text" id="alt_text" name="alt_text"' . pv_attr('alt_text') . '>');
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">5</span>Pricing</summary>
        <?php
          fld('Show pricing?', 'show_pricing',
              'Whether this email displays pricing at all. Choose No to omit the price fields.',
              '5-pricing',
              '<select id="show_pricing" name="show_pricing"><option value="">—</option><option value="yes"' . pv_sel('show_pricing', 'yes') . '>Yes</option><option value="no"' . pv_sel('show_pricing', 'no') . '>No</option></select>');
          fld('Original price', 'original_price',
              'The pre-discount / list price, if you are showing a strike-through.',
              '5-pricing',
              '<input type="text" id="original_price" name="original_price"' . pv_attr('original_price') . '>');
          fld('Sale / final price', 'sale_price',
              'The price the customer actually pays.',
              '5-pricing',
              '<input type="text" id="sale_price" name="sale_price"' . pv_attr('sale_price') . '>');
          fld('Discount', 'discount',
              'How the discount reads (e.g. "$50 off" or "20% off") — must reconcile with the prices above.',
              '5-pricing',
              '<input type="text" id="discount" name="discount"' . pv_attr('discount') . '>');
          fld('Promo code', 'promo_code',
              'The promo code to display, if any.',
              '5-pricing',
              '<input type="text" id="promo_code" name="promo_code"' . pv_attr('promo_code') . '>');
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">6</span>Call to action</summary>
        <?php
          fld('CTA 1 label', 'cta1_label',
              'The button text for the primary call to action (e.g. "Shop now").',
              '6-call-to-action',
              '<input type="text" id="cta1_label" name="cta1_label" placeholder="Shop now"' . pv_attr('cta1_label') . '>');
          fld('CTA 1 destination', 'cta1_dest',
              'Where the primary button links — brand site, marketplace, or other URL.',
              '6-call-to-action',
              '<input type="text" id="cta1_dest" name="cta1_dest" placeholder="https://…"' . pv_attr('cta1_dest') . '>');
          fld('CTA 2 label', 'cta2_label',
              'Optional second CTA button text. Leave blank to omit this CTA.',
              '6-call-to-action',
              '<input type="text" id="cta2_label" name="cta2_label"' . pv_attr('cta2_label') . '>');
          fld('CTA 2 destination', 'cta2_dest',
              'Where the second button links. Leave blank to omit this CTA.',
              '6-call-to-action',
              '<input type="text" id="cta2_dest" name="cta2_dest"' . pv_attr('cta2_dest') . '>');
          fld('CTA 3 label', 'cta3_label',
              'Optional third CTA button text. Leave blank to omit this CTA.',
              '6-call-to-action',
              '<input type="text" id="cta3_label" name="cta3_label"' . pv_attr('cta3_label') . '>');
          fld('CTA 3 destination', 'cta3_dest',
              'Where the third button links. Leave blank to omit this CTA.',
              '6-call-to-action',
              '<input type="text" id="cta3_dest" name="cta3_dest"' . pv_attr('cta3_dest') . '>');
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">7</span>Structure &amp; starting point</summary>
        <?php
          fld('Start from a template?', 'template',
              'Whether to base this on an existing template (newsletter / promo) or build fresh.',
              '7-structure--starting-point',
              '<select id="template" name="template"><option value="">—</option><option value="newsletter"' . pv_sel('template', 'newsletter') . '>Newsletter</option><option value="promo"' . pv_sel('template', 'promo') . '>Promo</option><option value="none — build fresh"' . pv_sel('template', 'none — build fresh') . '>None — build fresh</option></select>');
          fld('Sections to include', 'f_sections',
              'Optional. Leave blank for a minimal email (hero, headline, body, CTA) — the build won\'t add tech-specs/review/membership blocks on its own; tick the ones you want here. Header and footer are always included. Options are read live from the section files in email-design-system/sections/; anything custom goes in Notes (§8).',
              '7-structure--starting-point',
              sections_checks());
          fld('Anything to exclude', 'exclude',
              'Any blocks or elements to deliberately leave out.',
              '7-structure--starting-point',
              '<input type="text" id="exclude" name="exclude"' . pv_attr('exclude') . '>');
        ?>
      </details>

      <details class="fs" open>
        <summary><span class="num">8</span>Notes for the builder</summary>
        <?php
          fld('Notes', 'notes',
              'Anything specific to this send the builder should know — constraints, must-include lines, tone notes. Leave blank if none.',
              '8-notes-for-the-builder',
              '<textarea id="notes" name="notes">' . pv_text('notes') . '</textarea>');
        ?>
      </details>

      <div class="actions" style="display:flex; gap:12px; flex-wrap:wrap;">
        <button type="submit" name="do" value="generate" id="btn-generate" class="btn">Save &amp; generate</button>
        <button type="submit" name="do" value="save" id="btn-save" class="btn btn--ghost">Save</button>
      </div>
    </form>

  <?php else: ?>
    <h1>New email brief</h1>
    <p class="lede">Describe your campaign and we&rsquo;ll draft the brief for you to review &mdash; or open a saved one.</p>

    <form method="post" action="" id="vision-form" data-overlay="parse" class="vision">
      <input type="hidden" name="action" value="parse">
      <label for="vision">Describe your campaign</label>
      <textarea id="vision" name="vision" rows="5" required placeholder="e.g. A Father&rsquo;s Day promo for the Halo Collar 5, $50 off through Sunday, aimed at people who don&rsquo;t own one yet. Warm and reassuring, with a tech-specs section."></textarea>
      <div class="actions"><button type="submit" class="btn">Draft the brief &rarr;</button></div>
    </form>

    <?php $saved = brief_files(); if ($saved): ?>
      <div class="lp-or"><span>or open a saved brief</span></div>
      <div class="loadbar">
        <div class="combo" id="brief-combo">
          <input type="text" id="brief-search" placeholder="Search saved briefs…" aria-label="Search saved briefs" autocomplete="off" aria-expanded="false" aria-controls="brief-list">
          <ul class="combo-list" id="brief-list" role="listbox">
            <?php foreach ($saved as $b):
              $bbase = preg_replace('/\.md$/', '', $b['file']);
              $hay = strtolower($b['title'] . ' ' . $b['file']); ?>
              <li role="option" tabindex="0"
                  data-base="<?php echo htmlspecialchars($bbase, ENT_QUOTES, 'UTF-8'); ?>"
                  data-title="<?php echo htmlspecialchars($b['title'], ENT_QUOTES, 'UTF-8'); ?>"
                  data-search="<?php echo htmlspecialchars($hay, ENT_QUOTES, 'UTF-8'); ?>">
                <span class="t"><?php echo htmlspecialchars($b['title'], ENT_QUOTES, 'UTF-8'); ?></span>
                <span class="d"><?php echo htmlspecialchars($b['when'], ENT_QUOTES, 'UTF-8'); ?></span>
              </li>
            <?php endforeach; ?>
            <li class="combo-empty" hidden>No matching briefs.</li>
          </ul>
        </div>
        <div class="brief-actions" id="brief-actions" hidden>
          <a class="btn btn--ghost" id="act-edit" href="#">Edit</a>
          <a class="btn btn--ghost" id="act-copy" href="#">Copy</a>
          <form method="post" action="" id="act-delete-form" data-no-overlay style="margin:0; display:inline;"
                onsubmit="return confirm('Delete this brief and its generated email? This cannot be undone.');">
            <input type="hidden" name="action" value="delete">
            <input type="hidden" name="base" id="act-delete-base" value="">
            <button type="submit" class="btn btn--danger">Delete</button>
          </form>
        </div>
      </div>
    <?php endif; ?>
    <p class="lp-blank"><a href="form.php?new">Start a blank brief instead &rarr;</a></p>
<?php endif; ?>

    <div class="pg-loading" id="pg-loading" aria-hidden="true" role="status" aria-live="polite">
      <div class="pg-loading__card">
        <div class="pg-loading__spinner"></div>
        <p class="pg-loading__msg" id="pg-loading-msg">Working&hellip;</p>
        <p class="pg-loading__sub" id="pg-loading-sub">This can take a minute or two. Please don&rsquo;t refresh, hit back, or close this tab.</p>
      </div>
    </div>

    <div class="toast" id="toast" role="status" aria-live="polite" aria-hidden="true">
      <span class="toast__icon" id="toast-icon">&#10003;</span>
      <div class="toast__body">
        <strong class="toast__title" id="toast-title">Saved</strong>
        <span class="toast__msg" id="toast-msg"></span>
      </div>
    </div>
  </main>
  <script>
    (function () {
      var overlay = document.getElementById('pg-loading');
      var forms = document.querySelectorAll('form[method="post"]:not([data-no-overlay])');
      if (!overlay || !forms.length) return;
      var msgEl = document.getElementById('pg-loading-msg');
      var subEl = document.getElementById('pg-loading-sub');
      var sets = {
        generate: {
          sub: 'This can take a minute or two. Please don’t refresh, hit back, or close this tab — your email is being generated.',
          msgs: [
            'Waking up the email engine…',
            'Reading every rule (yes, all of them)…',
            'Choosing words that don’t use em dashes…',
            'Writing your email…',
            'Wrestling Outlook into submission…',
            'Making the button bulletproof…',
            'Double-checking the pricing math…',
            'Running the validators…',
            'Doing stuff. Important stuff…',
            'Almost there — hang tight…'
          ]
        },
        send: {
          sub: 'Sending the test email through Braze — this is quick. Please don’t refresh or hit back.',
          msgs: ['Handing it to Braze…', 'Sending to the test segment…', 'Almost there…']
        },
        edit: {
          sub: 'Applying your edit and re-checking every rule. Please don’t refresh, hit back, or close this tab.',
          msgs: ['Reading your change…', 'Revising the email…', 'Keeping the facts verbatim…', 'Re-running the validators…', 'Almost there — hang tight…']
        },
        save: {
          sub: 'Saving your brief — this is quick.',
          msgs: ['Saving the brief…']
        },
        parse: {
          sub: 'Reading your description and drafting the brief. This takes a few seconds.',
          msgs: ['Reading your description…', 'Picking the segment and sections…', 'Drafting the copy…', 'Filling in the fields…', 'Almost there…']
        }
      };
      var submitting = false;
      var timer = null;
      Array.prototype.forEach.call(forms, function (form) {
        form.addEventListener('submit', function (e) {
          if (submitting) { e.preventDefault(); return; }   // block any second submit
          submitting = true;
          var btn = (e.submitter && e.submitter.type === 'submit') ? e.submitter : form.querySelector('button[type="submit"]');
          // NOTE: do NOT set btn.disabled here — a disabled submit button drops its name/value
          // from the POST, which would strip do=save and make "Save" fall through to generate.
          // The `submitting` guard already blocks double-submits.
          if (btn) { btn.setAttribute('data-orig', btn.textContent); btn.textContent = 'Working…'; }
          var which = (e.submitter && e.submitter.value) || form.getAttribute('data-overlay') || 'generate';
          var set = sets[which] || sets.generate;
          if (subEl) subEl.textContent = set.sub;
          var i = 0;
          if (msgEl) msgEl.textContent = set.msgs[0];
          overlay.classList.add('show');
          overlay.setAttribute('aria-hidden', 'false');
          timer = setInterval(function () { i = (i + 1) % set.msgs.length; if (msgEl) msgEl.textContent = set.msgs[i]; }, 2600);
        });
      });
      // restore state if the user comes back via the bfcache (back button)
      window.addEventListener('pageshow', function (ev) {
        if (ev.persisted) {
          submitting = false;
          if (timer) clearInterval(timer);
          overlay.classList.remove('show');
          overlay.setAttribute('aria-hidden', 'true');
          Array.prototype.forEach.call(forms, function (form) {
            var btn = form.querySelector('button[type="submit"]');
            if (btn) { btn.disabled = false; if (btn.getAttribute('data-orig')) btn.textContent = btn.getAttribute('data-orig'); }
          });
        }
      });
    })();

    /* saved-briefs picker: search + SELECT a brief, then act on it (Edit / Copy / Delete) */
    (function () {
      var combo = document.getElementById('brief-combo');
      if (!combo) return;
      var input   = document.getElementById('brief-search');
      var list    = document.getElementById('brief-list');
      var items   = Array.prototype.slice.call(list.querySelectorAll('li[role="option"]'));
      var empty   = list.querySelector('.combo-empty');
      var actions = document.getElementById('brief-actions');
      var editA   = document.getElementById('act-edit');
      var copyA   = document.getElementById('act-copy');
      var delBase = document.getElementById('act-delete-base');
      combo.classList.add('js-combo');                 // turn the visible list into a dropdown

      function open()  { combo.classList.add('open'); input.setAttribute('aria-expanded', 'true'); }
      function clearActive() { items.forEach(function (li) { li.classList.remove('active'); }); }
      function close() { combo.classList.remove('open'); input.setAttribute('aria-expanded', 'false'); clearActive(); }
      function visible() { return items.filter(function (li) { return !li.hidden; }); }
      function filter() {
        var q = input.value.trim().toLowerCase(), shown = 0;
        items.forEach(function (li) {
          var ok = q === '' || li.getAttribute('data-search').indexOf(q) !== -1;
          li.hidden = !ok; if (ok) shown++;
        });
        if (empty) empty.hidden = shown !== 0;
        clearActive();
      }
      function select(li) {
        if (!li) return;
        var base = li.getAttribute('data-base'), title = li.getAttribute('data-title');
        if (editA)   editA.href = 'form.php?edit=' + encodeURIComponent(base);
        if (copyA)   copyA.href = 'form.php?copy=' + encodeURIComponent(base);
        if (delBase) delBase.value = base;
        if (actions) actions.hidden = false;
        input.value = title;
        items.forEach(function (x) { x.classList.remove('selected'); });
        li.classList.add('selected');
        close();
      }

      input.addEventListener('focus', open);
      input.addEventListener('input', function () { filter(); open(); });
      input.addEventListener('keydown', function (e) {
        var vis = visible(), cur = list.querySelector('li.active'), idx = cur ? vis.indexOf(cur) : -1;
        if (e.key === 'ArrowDown') { e.preventDefault(); open(); if (vis.length) { clearActive(); idx = (idx + 1) % vis.length; vis[idx].classList.add('active'); vis[idx].scrollIntoView({ block: 'nearest' }); } }
        else if (e.key === 'ArrowUp') { e.preventDefault(); if (vis.length) { clearActive(); idx = (idx <= 0 ? vis.length - 1 : idx - 1); vis[idx].classList.add('active'); vis[idx].scrollIntoView({ block: 'nearest' }); } }
        else if (e.key === 'Enter') { e.preventDefault(); select(cur || vis[0]); }
        else if (e.key === 'Escape') { close(); }
      });
      items.forEach(function (li) { li.addEventListener('click', function () { select(li); }); });
      document.addEventListener('click', function (e) { if (!combo.contains(e.target)) close(); });
      filter();
    })();

    /* nice toast + Save-without-leaving-the-page (AJAX draft save) */
    (function () {
      var toastEl = document.getElementById('toast');
      function toast(title, msg, isError) {
        if (!toastEl) return;
        document.getElementById('toast-title').textContent = title;
        document.getElementById('toast-msg').textContent = msg || '';
        document.getElementById('toast-icon').innerHTML = isError ? '&#9888;' : '&#10003;';
        toastEl.classList.toggle('toast--error', !!isError);
        toastEl.classList.add('show');
        toastEl.setAttribute('aria-hidden', 'false');
        clearTimeout(toastEl._t);
        toastEl._t = setTimeout(function () {
          toastEl.classList.remove('show');
          toastEl.setAttribute('aria-hidden', 'true');
        }, 3600);
      }

      var form = document.getElementById('brief-form');
      if (!form) return;

      // a required field hidden inside a collapsed section can't show its validation
      // bubble — open the offending section first.
      function openInvalidSection() {
        var bad = form.querySelector(':invalid');
        if (bad) { var d = bad.closest('details'); if (d) d.open = true; }
      }
      var genBtn = document.getElementById('btn-generate');
      if (genBtn) genBtn.addEventListener('click', openInvalidSection);

      var saveBtn = document.getElementById('btn-save');
      if (!saveBtn || !window.fetch) return;          // no fetch → Save does a normal submit (saved page)
      saveBtn.addEventListener('click', function (e) {
        e.preventDefault();                          // save in place — no page reload
        openInvalidSection();
        if (!form.reportValidity()) return;          // still honor the required Brief name
        var fd = new FormData(form);
        fd.set('do', 'save');                        // FormData omits submit buttons; set it explicitly
        var orig = saveBtn.textContent;
        saveBtn.textContent = 'Saving…';
        fetch(form.action || window.location.href, {
          method: 'POST',
          headers: { 'X-Requested-With': 'XMLHttpRequest' },
          body: fd
        }).then(function (r) { return r.json(); }).then(function (data) {
          saveBtn.textContent = orig;
          if (data && data.ok) {
            var ed = form.querySelector('input[name="editing"]');
            if (ed && data.base) ed.value = data.base;   // further saves now UPDATE this brief (no duplicate)
            toast('Brief saved', data.name ? '“' + data.name + '” saved as a draft.' : 'Saved as a draft.');
          } else {
            toast('Save failed', (data && data.error) ? data.error : 'Could not save the brief.', true);
          }
        }).catch(function () {
          saveBtn.textContent = orig;
          toast('Save failed', 'Network error while saving.', true);
        });
      });
    })();

    /* email preview: Desktop (600px) / Mobile (375px) width toggle */
    (function () {
      Array.prototype.forEach.call(document.querySelectorAll('.email-preview'), function (wrap) {
        var frame = wrap.querySelector('.email-preview__frame');
        var btns = wrap.querySelectorAll('.vw-btn');
        if (!frame || !btns.length) return;
        Array.prototype.forEach.call(btns, function (btn) {
          btn.addEventListener('click', function () {
            frame.style.width = btn.getAttribute('data-w') + 'px';
            Array.prototype.forEach.call(btns, function (b) { b.classList.remove('is-active'); });
            btn.classList.add('is-active');
          });
        });
      });
    })();
  </script>
</body>
</html>
